ISUCON13_MYSQL_DIALCONFIG_NET="tcp"
ISUCON13_MYSQL_DIALCONFIG_ADDRESS="isucon2"
ISUCON13_MYSQL_DIALCONFIG_PORT="3306"
ISUCON13_MYSQL_DIALCONFIG_USER="isucon"
ISUCON13_MYSQL_DIALCONFIG_DATABASE="isupipe"
ISUCON13_MYSQL_DIALCONFIG_PARSETIME="true"
ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS="35.74.152.186" # isucon3
ISUCON13_POWERDNS_DISABLED="false"

GOOGLE_CLOUD_PROJECT=triple-innocent
GOOGLE_APPLICATION_CREDENTIALS=/home/isucon/service-account-credential.json
