ISUCON13_MYSQL_DIALCONFIG_NET="tcp"
ISUCON13_MYSQL_DIALCONFIG_ADDRESS="isucon2"
ISUCON13_MYSQL_DIALCONFIG_PORT="3306"
ISUCON13_MYSQL_DIALCONFIG_USER="isucon"
ISUCON13_MYSQL_DIALCONFIG_DATABASE="isupipe"
ISUCON13_MYSQL_DIALCONFIG_PARSETIME="true"
if [[ "$HOSTNAME" == isucon1 ]]; then
  ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS="18.176.153.139"
elif [[ "$HOSTNAME" == isucon2 ]]; then
  ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS="18.179.101.66"
elif [[ "$HOSTNAME" == isucon3 ]]; then
  ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS="35.74.152.186"
else
  echo "Invalid host"
  exit 1
fi
ISUCON13_POWERDNS_DISABLED="false"

GOOGLE_CLOUD_PROJECT=triple-innocent
GOOGLE_APPLICATION_CREDENTIALS=/home/isucon/service-account-credential.json
